"""init

Revision ID: 06b63b44bf36
Revises: 0a0a2f5d510d
Create Date: 2019-12-27 15:06:40.067685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b63b44bf36'
down_revision = '0a0a2f5d510d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
