"""init

Revision ID: a79ce37db434
Revises: a476729f46cb
Create Date: 2019-12-27 11:26:34.543970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79ce37db434'
down_revision = 'a476729f46cb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
