"""init

Revision ID: fc2dfc0ebb24
Revises: 06b63b44bf36
Create Date: 2019-12-27 15:07:24.338985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2dfc0ebb24'
down_revision = '06b63b44bf36'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
