"""init

Revision ID: 559b128e202a
Revises: 7dcd4ad9f4a2
Create Date: 2019-12-26 20:46:28.994925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559b128e202a'
down_revision = '7dcd4ad9f4a2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
